### ISSUE TITLE
Freeze tf probability version to avoid syntax error with tfd.MultivariateNormalDiag

### ISSUE THREAD

**Issue by r-shruthi11** [dattalab/jax-moseq#24]
Notice the difference between [v0.20](https://github.com/tensorflow/probability/blob/v0.20.0/tensorflow_probability/python/distributions/mvn_diag.py#L127) and [v0.19](https://github.com/dattalab/jax-moseq/blob/main/jax_moseq/models/keypoint_slds/log_prob.py#L66) where the args  in  `tfd.MultivariateNormalDiag(Y_bar, None, sigma).log_prob(Y)` are different. The syntax used in https://github.com/dattalab/jax-moseq/blob/main/jax_moseq/models/keypoint_slds/log_prob.py#L66 is currently deprecated.

**Comment by calebweinreb** [comment]
Thanks for the heads up!
